server:
  port: 3001
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_account?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
mybatis:
  mapper-locations: classpath:mapper/*.xml
